### ISSUE TITLE
How to evaluate the performance of your provided PV-RCNN model according to the segmentation distance on STF dataset?[0-30m][30-50m][50-80m]  Please!

### ISSUE THREAD

**Issue by Qizhi697** [SysCV/LiDAR_snow_sim#11]

**Comment by MartinHahner** [comment]
Replace pcdet/datasets/kitti/kitti_object_eval_python/[eval.py](https://github.com/SysCV/LiDAR_snow_sim/files/9195956/eval.py.zip).
In this file, you can search for "distance" and you will find how it is implemented.

**Comment by esther-ET** [comment]
> _No description provided._

你好，请问这个eval是不是需要自己写啊，我看openpcdet的metric全部都是KITTI的，但论文的metric貌似是waymo的，而且工程里面好像没找着，感谢你的回复
