### ISSUE TITLE
Question about the intensity of snow in STF data

### ISSUE THREAD

**Issue by cuge1995** [SysCV/LiDAR_snow_sim#14]
As state in the paper `We split the 3916 samples in the snow test set based on the intensity of snowfall into two different subsets, termed light snowfall and heavy snowfall, with 2512 and 1404 samples respectively.`

However, I can't find it. Can you opensource its index in the STF?

**Comment by MartinHahner** [comment]
The splits are given [here](https://github.com/SysCV/LiDAR_snow_sim/tree/main/splits).
