### ISSUE TITLE
Tutorial for snow simulation on other datasets

### ISSUE THREAD

**Issue by jihanyang** [SysCV/LiDAR_snow_sim#15]
Hello Martin,
Thanks for your great work. May I know whether there is a tutorial about running the snow simulation on other dataset to create new data?

**Comment by MartinHahner** [comment]
Hi Jihan,

no, there is onle the readme.

I suggest you follow the getting started[getting started](https://github.com/SysCV/LiDAR_snow_sim#getting-started) section and then familiarize yourself with the code in [tools](https://github.com/SysCV/LiDAR_snow_sim/tree/main/tools) directory.

Greets, Martin
