### ISSUE TITLE
How to get the output snow+wet pointcloud files?

### ISSUE THREAD

**Issue by dinghuixiang-github** [SysCV/LiDAR_snow_sim#19]
Hello，thank you for your excellent work, it is exactly what I need.
I have seen the https://github.com/MartinHahner/LiDAR_fog_sim and https://github.com/SysCV/LiDAR_snow_sim. In the fog simulation model, there is a fog_simulation.py to input clear pointcloud files and output fog pointcloud files. While, is there any way to achieve similar functionality in the snow+wet simulation model, or could you please tell me how to achieve this? Hoping for your reply.

**Comment by RhythmOfTheRain-Byte** [comment]
> Hello，thank you for your excellent work, it is exactly what I need. I have seen the https://github.com/MartinHahner/LiDAR_fog_sim and https://github.com/SysCV/LiDAR_snow_sim. In the fog simulation model, there is a fog_simulation.py to input clear pointcloud files and output fog pointcloud files. While, is there any way to achieve similar functionality in the snow+wet simulation model, or could you please tell me how to achieve this? Hoping for your reply.

Excuse me, I was wondering if you've found a solution to this problem.
I have a similar problem. Could you tell me about it?
Thank you very much.
