### ISSUE TITLE
Excuse me, where is the path to save the point cloud file after adding snowflake simulation noise? Thank you！

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [SysCV/LiDAR_snow_sim#20]
Excuse me, where is the path to save the point cloud file after adding snowflake simulation noise? Thank you！

**Comment by MartinHahner** [comment]
Hi (I guess Pengfei from the email),
you could write your own export function to save the point cloud (`pc`) in your desired format and call that function at the end of `show_pointcloud`, e.g. here:
https://github.com/SysCV/LiDAR_snow_sim/blob/main/pointcloud_viewer.py#L3017
Greets, Martin

**Comment by RhythmOfTheRain-Byte** [comment]
Thank you very much！

**Comment by RhythmOfTheRain-Byte** [comment]
> Hi (I guess Pengfei from the email), you could write your own export function to save the point cloud (`pc`) in your desired format and call that function at the end of `show_pointcloud`, e.g. here: https://github.com/SysCV/LiDAR_snow_sim/blob/main/pointcloud_viewer.py#L3017 Greets, Martin

Thanks for your time!
In the process of saving the data, I just saved the XYZI 4D information of the point cloud data, which were saved as a bin file.
The size of the saved KITTI single frame data is 16k, which is much smaller than the 1.*M of the original KITTI dataset, I would like to know , will this affect the subsequent training?

**Comment by esther-ET** [comment]
> Excuse me, where is the path to save the point cloud file after adding snowflake simulation noise? Thank you！

Hi， may I know how do you get the simulation of snow+wet and which .py should I run to achieve? Thank you very much!
