### ISSUE TITLE
The problem of Batch data saving

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [SysCV/LiDAR_snow_sim#25]
Excuse me，I'm trying to save the point cloud data after adding rain and snow noise by running the code. 
But in the actual code, I can only click on the button to show the point cloud for the next frame one by one.
Could you tell me how to save data in bulk without having to click on it one at a time?
Thank you very much!

**Comment by tianyolanda** [comment]
> Excuse me，I'm trying to save the point cloud data after adding rain and snow noise by running the code. But in the actual code, I can only click on the button to show the point cloud for the next frame one by one. Could you tell me how to save data in bulk without having to click on it one at a time? Thank you very much!

Hi, have you solved this problem? Could you please tell me how to train the dataset and get the data to save in a file? Thank you very much!
