### ISSUE TITLE
Hello, I can't reproduce the result in PV-RCNN model.

### ISSUE THREAD

**Issue by handsomeli1898** [SysCV/LiDAR_snow_sim#28]
Hello, I used the code provided, but there exists gap between the results I reproduced and the results the paper provided.

# This is the result I reproduced in PV-RCNN model.
|-|test_clear|test_snow_light|test_snow_heavy|
|-------|-------|-------|-------|
|None|45.04|41.20|39.15|
|Snow|44.60|40.60|**39.33**|
|Wet|45.19|40.65|41.07|
|Snow+Wet|44.85|40.79|41.33|

# This is the result the paper reported in PV-RCNN model.
|-|test_clear|test_snow_light|test_snow_heavy|
|-------|-------|-------|-------|
|None|45.36|41.13|39.69|
|Snow|45.61|41.20|**41.61**|
|Wet|44.81|41.07|**40.03**|
|Snow+Wet|45.71|41.79|41.79|

And I used the model you have provided experiments/snow+wet/pc_rcnn.pth, and the result is:
|test_clear|test_snow_light|test_snow_heavy|
|-------|-------|-------|
|**42.15**|40.12|41.95|

Looking forward to your reply!

**Comment by zyrant** [comment]
hello, 
I am having trouble with the pcdet part code, do you know where there is any tutorial?
