### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by LuPaoPao** [SysCV/LiDAR_snow_sim#3]
Thank you for your excellent paper in this field. Will the training code in the paper be made public? If it does, it will help us greatly in our scientific research.

**Comment by MartinHahner** [comment]
You can train via [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) and find our data loading here: [dense_dataset.py](https://github.com/MartinHahner/OpenPCDet/blob/0b8c57e321751b4712c233d008c8cbbed06419f5/pcdet/datasets/dense/dense_dataset.py)

**Comment by LuPaoPao** [comment]
Thanks~
