### ISSUE TITLE
Why did not `max_intensity` come from calibration file?

### ISSUE THREAD

**Issue by Beastmaster** [SysCV/LiDAR_snow_sim#4]
Hi, 
in file: `tools/snowfall/simulation.py`, line123 - 126:  
```
        if channel in [53, 55, 56, 58]:
            max_intensity = 230
        else:
            max_intensity = 255
```
Why did not `max_intensity` come from calibration file?

Thank you!

**Comment by Beastmaster** [comment]
I'm also confused on "Algorithm1 LiDAR simulation", line25. 
![image](https://user-images.githubusercontent.com/5296304/175877453-5b83fcf5-71b6-4c73-8bea-ab38f5a5a1d4.png)
Why add corrected  i_max to max received power(intnesity)?

**Comment by MartinHahner** [comment]
> Why did not `max_intensity` come from calibration file?

It is the hard-coded version of what is in our calibration file. 😉

**Comment by Beastmaster** [comment]
Do you have any clue to setup this `max_intensity`? :grin:
