### ISSUE TITLE
Why is the beam divergence correction like that?

### ISSUE THREAD

**Issue by Beastmaster** [SysCV/LiDAR_snow_sim#5]
I can find nowhere about this equation (Chapter3, eq(2)): 

![image](https://user-images.githubusercontent.com/5296304/175880313-73d2c0ed-5a89-4376-8ffb-d351c863b05f.png)

Correction factors are listed for each beam. Did I lose something?

**Comment by MartinHahner** [comment]
From [the manual](https://www.manualslib.com/manual/1988532/Velodyne-Hdl-64e-S3.html):

<img width="905" alt="grafik" src="https://user-images.githubusercontent.com/14181188/175953596-5d9155b7-70a2-4660-ae55-57ab94eb01ff.png">

**Comment by yanconglin** [comment]
Hi, a followup question
why[ this line ](https://github.com/SysCV/LiDAR_snow_sim/blob/760c42e46e10c6aa6b57048c5c1892289f0c2d08/tools/snowfall/simulation.py#L128)does not align with the equation shown above?  I am referring to this: (1 - d_orig/120)**2.
