### ISSUE TITLE
`beta_0` is reflectivity?

### ISSUE THREAD

**Issue by Beastmaster** [SysCV/LiDAR_snow_sim#6]
I noticed that in `tools/snowfall/simulation.py` there is a `beta_0`. I suppose it to be reflectivity. Why it's fixed to `beta_0 = 1 * 10 ** -6 / PI`

**Comment by MartinHahner** [comment]
It is the same value we empirically found works well in our earlier work.
https://github.com/MartinHahner/LiDAR_fog_sim


<img width="412" alt="grafik" src="https://user-images.githubusercontent.com/14181188/176087456-a3106796-4046-4bff-a6e2-6aacb97214aa.png">

**Comment by MartinHahner** [comment]
Please use the [Q&A](https://github.com/SysCV/LiDAR_snow_sim/discussions/categories/q-a) functionality for such questions in the future.
