### ISSUE TITLE
How to augment the KITTI bin file?

### ISSUE THREAD

**Issue by cuge1995** [SysCV/LiDAR_snow_sim#7]
Thanks for the great work!
The kitti bin only have x,y,z,intensity(not (x, y, z, intensity, channel)), how to augment it with snowfall in your paper?

**Comment by MartinHahner** [comment]
Good question. 

You can either try to reconstruct the channel information geometrically using the vertical and horizontal resolution of the LiDAR sensor or you randomly use one of the 64 sampled snowflake disks for every point.

The first option is more sophisticated to implement.

The second option is easier to implement but will break consistency. 
Nevertheless, I think the snowfall clutter should not look drastically different that way.

**Comment by dinghuixiang-github** [comment]
> 

 I have the same problem.Did you solve it? Could you please tell me how to achieve?
