### ISSUE TITLE
How to add the snow+wet after running pointcloud_viewer.py? Q&A

### ISSUE THREAD

**Issue by cuge1995** [SysCV/LiDAR_snow_sim#8]
Only a `add our fog`, no `add our snow+wet`

**Comment by MartinHahner** [comment]
Press the button `apply snow` and then the button `apply wet`. 😄

**Comment by cuge1995** [comment]
I don't see any `apply snow` and `apply wet` button after running pointcloud_viewer.py.

**Comment by cuge1995** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/48620704/177963934-d5a1b7c2-91ea-4a6f-8e98-29f10078612f.png">
This is my window, what's wrong with me?

**Comment by MartinHahner** [comment]
Which dataset did you load? KITTI?

If you want to augment KITTI, you have to make changes in the code.
The current code only works with the STF dataset.
It won't work out of the box for other datasets.

**Comment by esther-ET** [comment]
Hello, Mr. Hahner, thank you so much for this project. I have the same problem just like the cuge1995's, but I have used the STF.  I use the STF by loading it through the button "choose custom directiry", and I have got the unzipped file called SeeingThroughFogCompressedExtracted with 12977 bin documents.

**Comment by esther-ET** [comment]
Hi, @MartinHahner!
I have some question about the Gui, too. I can't apply the snow button and the wet button at the same time, and is it wrong? Also only when I choose the snow, I can apply snow+wet, but it doesn't look effective that the point cloud has no difference from the snow one after I load the result.
