### ISSUE TITLE
classes in Seeing Through Fog dataset

### ISSUE THREAD

**Issue by barzanisar** [SysCV/LiDAR_snow_sim#9]
Hey Martin,

Which classes from Seeing through fog dataset did you group into the kitti "Car", "Pedestrian", "Cyclist" classes? Your OpenPCDet dense_dataset.py assumes that the groundtruth labels for dense dataset are "Car", "Pedestrian", "Cyclist".

Thanks

**Comment by MartinHahner** [comment]
Hi Barza,

we mapped the classes as follows (see [here](https://github.com/MartinHahner/OpenPCDet/blob/0b8c57e321751b4712c233d008c8cbbed06419f5/pcdet/utils/object3d_kitti.py#L3-L8)):
```python
DENSE_TO_KITTI_LABEL = {'PassengerCar': 'Car',
                        'Pedestrian': 'Pedestrian',
                        'RidableVehicle': 'Cyclist',
                        'LargeVehicle': 'Van',
                        'Vehicle': 'Van',
                        'DontCare': 'DontCare'}
```
